### ISSUE TITLE
Count limit is not applied when no keyword is specified

### ISSUE THREAD

**Issue by dvergnes** [paulr978/AgentLogViewer#1]
When the limit is specified in the query parameter, it is expected that will be honored whether a keyword is specified or not.

**How to reproduce**
 - curl "http://localhost:3000/log/tail?fileName=test/test_1mb.log&count=10"

**Expected behavior**
Only the last 10 lines of the file are returned

**Current behavior**
All lines of the file are returned

**Comment by paulr978** [comment]
Thanks Denis! Issue is resolved and int test created to support. Thanks for raising this!
